sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t sergiuoxigen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sergiuoxigen/docker-react npm run test
